export const initializeEmployeeFormData = () => {
  return {
    // email: "",
    name: "",
    employee_id: "",
    email: "",
    phone_number: "",
    position: "",
    manager: "",
    team_name: "",
    company_name: "",
    dob: "",
    doj: "",
    cohesive_role: "",
    cohesive_user_id: "",
    cohesive_user_name: "",
    cohesive_workspace_id: "",
    cohesive_workspace_name: "",
    gender: "Male",
    // related_people: {
    //   peer: [],
    //   manager: [],
    //   hr_review: [],
    //   external: [],
    // },
    // review_status: {
    //   self_review: "Pending",
    //   peer_review: "Pending",
    //   manager_review: "Pending",
    //   hr_review: "Pending",
    //   external_review: "Pending",
    // },
    // nominations: {
    //   peer_review: [],
    //   manager_review: [],
    //   hr_review: [],
    //   external_review: [],
    // },
  };
};
